/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as LoginRouteImport } from './../../routes/login'
import { Route as AuthenticatedRouteRouteImport } from './../../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as AuthenticatedMiFirmaRouteImport } from './../../routes/_authenticated/mi-firma'
import { Route as AuthenticatedDashboardRouteImport } from './../../routes/_authenticated/dashboard'
import { Route as AuthenticatedVisitasRegistroVisitaRouteImport } from './../../routes/_authenticated/visitas/registro-visita'
import { Route as AuthenticatedVisitasPortalCentralRouteImport } from './../../routes/_authenticated/visitas/portal-central'
import { Route as AuthenticatedSistemasRegistroProductividadRouteImport } from './../../routes/_authenticated/sistemas/registro-productividad'
import { Route as AuthenticatedSistemasMisEquiposRouteImport } from './../../routes/_authenticated/sistemas/mis-equipos'
import { Route as AuthenticatedSistemasAsignacionBienesRouteImport } from './../../routes/_authenticated/sistemas/asignacion-bienes'
import { Route as AuthenticatedSistemasAjustesRouteImport } from './../../routes/_authenticated/sistemas/ajustes'
import { Route as AuthenticatedSaludOcupacionalReportesRouteImport } from './../../routes/_authenticated/salud-ocupacional/reportes'
import { Route as AuthenticatedSaludOcupacionalRegistroConsultaRouteImport } from './../../routes/_authenticated/salud-ocupacional/registro-consulta'
import { Route as AuthenticatedSaludOcupacionalMisConsultasRouteImport } from './../../routes/_authenticated/salud-ocupacional/mis-consultas'
import { Route as AuthenticatedSaludOcupacionalInventarioMedicoRouteImport } from './../../routes/_authenticated/salud-ocupacional/inventario-medico'
import { Route as AuthenticatedSaludOcupacionalHistorialMedicoRouteImport } from './../../routes/_authenticated/salud-ocupacional/historial-medico'
import { Route as AuthenticatedSaludOcupacionalDescansoMedicoRouteImport } from './../../routes/_authenticated/salud-ocupacional/descanso-medico'
import { Route as AuthenticatedSaludOcupacionalAjustesRouteImport } from './../../routes/_authenticated/salud-ocupacional/ajustes'
import { Route as AuthenticatedHorasExtraRegistroHorasExtraRouteImport } from './../../routes/_authenticated/horas-extra/registro-horas-extra'
import { Route as AuthenticatedHorasExtraAprobacionHorasExtraRouteImport } from './../../routes/_authenticated/horas-extra/aprobacion-horas-extra'
import { Route as AuthenticatedHorasExtraAjustesRouteImport } from './../../routes/_authenticated/horas-extra/ajustes'
import { Route as AuthenticatedCrmQuimicosDashboardCrmRouteImport } from './../../routes/_authenticated/crm-quimicos/dashboard-crm'
import { Route as AuthenticatedAdministracionRolesRouteImport } from './../../routes/_authenticated/administracion/roles'
import { Route as AuthenticatedAdministracionGestionUsuariosRouteImport } from './../../routes/_authenticated/administracion/gestion-usuarios'
import { Route as AuthenticatedAdministracionAsignacionesRouteImport } from './../../routes/_authenticated/administracion/asignaciones'
import { Route as AuthenticatedAdministracionAjustesRouteImport } from './../../routes/_authenticated/administracion/ajustes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiFirmaRoute = AuthenticatedMiFirmaRouteImport.update({
  id: '/mi-firma',
  path: '/mi-firma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitasRegistroVisitaRoute =
  AuthenticatedVisitasRegistroVisitaRouteImport.update({
    id: '/visitas/registro-visita',
    path: '/visitas/registro-visita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitasPortalCentralRoute =
  AuthenticatedVisitasPortalCentralRouteImport.update({
    id: '/visitas/portal-central',
    path: '/visitas/portal-central',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemasRegistroProductividadRoute =
  AuthenticatedSistemasRegistroProductividadRouteImport.update({
    id: '/sistemas/registro-productividad',
    path: '/sistemas/registro-productividad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemasMisEquiposRoute =
  AuthenticatedSistemasMisEquiposRouteImport.update({
    id: '/sistemas/mis-equipos',
    path: '/sistemas/mis-equipos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemasAsignacionBienesRoute =
  AuthenticatedSistemasAsignacionBienesRouteImport.update({
    id: '/sistemas/asignacion-bienes',
    path: '/sistemas/asignacion-bienes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemasAjustesRoute =
  AuthenticatedSistemasAjustesRouteImport.update({
    id: '/sistemas/ajustes',
    path: '/sistemas/ajustes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalReportesRoute =
  AuthenticatedSaludOcupacionalReportesRouteImport.update({
    id: '/salud-ocupacional/reportes',
    path: '/salud-ocupacional/reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalRegistroConsultaRoute =
  AuthenticatedSaludOcupacionalRegistroConsultaRouteImport.update({
    id: '/salud-ocupacional/registro-consulta',
    path: '/salud-ocupacional/registro-consulta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalMisConsultasRoute =
  AuthenticatedSaludOcupacionalMisConsultasRouteImport.update({
    id: '/salud-ocupacional/mis-consultas',
    path: '/salud-ocupacional/mis-consultas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalInventarioMedicoRoute =
  AuthenticatedSaludOcupacionalInventarioMedicoRouteImport.update({
    id: '/salud-ocupacional/inventario-medico',
    path: '/salud-ocupacional/inventario-medico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalHistorialMedicoRoute =
  AuthenticatedSaludOcupacionalHistorialMedicoRouteImport.update({
    id: '/salud-ocupacional/historial-medico',
    path: '/salud-ocupacional/historial-medico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalDescansoMedicoRoute =
  AuthenticatedSaludOcupacionalDescansoMedicoRouteImport.update({
    id: '/salud-ocupacional/descanso-medico',
    path: '/salud-ocupacional/descanso-medico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaludOcupacionalAjustesRoute =
  AuthenticatedSaludOcupacionalAjustesRouteImport.update({
    id: '/salud-ocupacional/ajustes',
    path: '/salud-ocupacional/ajustes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHorasExtraRegistroHorasExtraRoute =
  AuthenticatedHorasExtraRegistroHorasExtraRouteImport.update({
    id: '/horas-extra/registro-horas-extra',
    path: '/horas-extra/registro-horas-extra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHorasExtraAprobacionHorasExtraRoute =
  AuthenticatedHorasExtraAprobacionHorasExtraRouteImport.update({
    id: '/horas-extra/aprobacion-horas-extra',
    path: '/horas-extra/aprobacion-horas-extra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHorasExtraAjustesRoute =
  AuthenticatedHorasExtraAjustesRouteImport.update({
    id: '/horas-extra/ajustes',
    path: '/horas-extra/ajustes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmQuimicosDashboardCrmRoute =
  AuthenticatedCrmQuimicosDashboardCrmRouteImport.update({
    id: '/crm-quimicos/dashboard-crm',
    path: '/crm-quimicos/dashboard-crm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracionRolesRoute =
  AuthenticatedAdministracionRolesRouteImport.update({
    id: '/administracion/roles',
    path: '/administracion/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracionGestionUsuariosRoute =
  AuthenticatedAdministracionGestionUsuariosRouteImport.update({
    id: '/administracion/gestion-usuarios',
    path: '/administracion/gestion-usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracionAsignacionesRoute =
  AuthenticatedAdministracionAsignacionesRouteImport.update({
    id: '/administracion/asignaciones',
    path: '/administracion/asignaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracionAjustesRoute =
  AuthenticatedAdministracionAjustesRouteImport.update({
    id: '/administracion/ajustes',
    path: '/administracion/ajustes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-firma': typeof AuthenticatedMiFirmaRoute
  '/administracion/ajustes': typeof AuthenticatedAdministracionAjustesRoute
  '/administracion/asignaciones': typeof AuthenticatedAdministracionAsignacionesRoute
  '/administracion/gestion-usuarios': typeof AuthenticatedAdministracionGestionUsuariosRoute
  '/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/crm-quimicos/dashboard-crm': typeof AuthenticatedCrmQuimicosDashboardCrmRoute
  '/horas-extra/ajustes': typeof AuthenticatedHorasExtraAjustesRoute
  '/horas-extra/aprobacion-horas-extra': typeof AuthenticatedHorasExtraAprobacionHorasExtraRoute
  '/horas-extra/registro-horas-extra': typeof AuthenticatedHorasExtraRegistroHorasExtraRoute
  '/salud-ocupacional/ajustes': typeof AuthenticatedSaludOcupacionalAjustesRoute
  '/salud-ocupacional/descanso-medico': typeof AuthenticatedSaludOcupacionalDescansoMedicoRoute
  '/salud-ocupacional/historial-medico': typeof AuthenticatedSaludOcupacionalHistorialMedicoRoute
  '/salud-ocupacional/inventario-medico': typeof AuthenticatedSaludOcupacionalInventarioMedicoRoute
  '/salud-ocupacional/mis-consultas': typeof AuthenticatedSaludOcupacionalMisConsultasRoute
  '/salud-ocupacional/registro-consulta': typeof AuthenticatedSaludOcupacionalRegistroConsultaRoute
  '/salud-ocupacional/reportes': typeof AuthenticatedSaludOcupacionalReportesRoute
  '/sistemas/ajustes': typeof AuthenticatedSistemasAjustesRoute
  '/sistemas/asignacion-bienes': typeof AuthenticatedSistemasAsignacionBienesRoute
  '/sistemas/mis-equipos': typeof AuthenticatedSistemasMisEquiposRoute
  '/sistemas/registro-productividad': typeof AuthenticatedSistemasRegistroProductividadRoute
  '/visitas/portal-central': typeof AuthenticatedVisitasPortalCentralRoute
  '/visitas/registro-visita': typeof AuthenticatedVisitasRegistroVisitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-firma': typeof AuthenticatedMiFirmaRoute
  '/administracion/ajustes': typeof AuthenticatedAdministracionAjustesRoute
  '/administracion/asignaciones': typeof AuthenticatedAdministracionAsignacionesRoute
  '/administracion/gestion-usuarios': typeof AuthenticatedAdministracionGestionUsuariosRoute
  '/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/crm-quimicos/dashboard-crm': typeof AuthenticatedCrmQuimicosDashboardCrmRoute
  '/horas-extra/ajustes': typeof AuthenticatedHorasExtraAjustesRoute
  '/horas-extra/aprobacion-horas-extra': typeof AuthenticatedHorasExtraAprobacionHorasExtraRoute
  '/horas-extra/registro-horas-extra': typeof AuthenticatedHorasExtraRegistroHorasExtraRoute
  '/salud-ocupacional/ajustes': typeof AuthenticatedSaludOcupacionalAjustesRoute
  '/salud-ocupacional/descanso-medico': typeof AuthenticatedSaludOcupacionalDescansoMedicoRoute
  '/salud-ocupacional/historial-medico': typeof AuthenticatedSaludOcupacionalHistorialMedicoRoute
  '/salud-ocupacional/inventario-medico': typeof AuthenticatedSaludOcupacionalInventarioMedicoRoute
  '/salud-ocupacional/mis-consultas': typeof AuthenticatedSaludOcupacionalMisConsultasRoute
  '/salud-ocupacional/registro-consulta': typeof AuthenticatedSaludOcupacionalRegistroConsultaRoute
  '/salud-ocupacional/reportes': typeof AuthenticatedSaludOcupacionalReportesRoute
  '/sistemas/ajustes': typeof AuthenticatedSistemasAjustesRoute
  '/sistemas/asignacion-bienes': typeof AuthenticatedSistemasAsignacionBienesRoute
  '/sistemas/mis-equipos': typeof AuthenticatedSistemasMisEquiposRoute
  '/sistemas/registro-productividad': typeof AuthenticatedSistemasRegistroProductividadRoute
  '/visitas/portal-central': typeof AuthenticatedVisitasPortalCentralRoute
  '/visitas/registro-visita': typeof AuthenticatedVisitasRegistroVisitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mi-firma': typeof AuthenticatedMiFirmaRoute
  '/_authenticated/administracion/ajustes': typeof AuthenticatedAdministracionAjustesRoute
  '/_authenticated/administracion/asignaciones': typeof AuthenticatedAdministracionAsignacionesRoute
  '/_authenticated/administracion/gestion-usuarios': typeof AuthenticatedAdministracionGestionUsuariosRoute
  '/_authenticated/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/_authenticated/crm-quimicos/dashboard-crm': typeof AuthenticatedCrmQuimicosDashboardCrmRoute
  '/_authenticated/horas-extra/ajustes': typeof AuthenticatedHorasExtraAjustesRoute
  '/_authenticated/horas-extra/aprobacion-horas-extra': typeof AuthenticatedHorasExtraAprobacionHorasExtraRoute
  '/_authenticated/horas-extra/registro-horas-extra': typeof AuthenticatedHorasExtraRegistroHorasExtraRoute
  '/_authenticated/salud-ocupacional/ajustes': typeof AuthenticatedSaludOcupacionalAjustesRoute
  '/_authenticated/salud-ocupacional/descanso-medico': typeof AuthenticatedSaludOcupacionalDescansoMedicoRoute
  '/_authenticated/salud-ocupacional/historial-medico': typeof AuthenticatedSaludOcupacionalHistorialMedicoRoute
  '/_authenticated/salud-ocupacional/inventario-medico': typeof AuthenticatedSaludOcupacionalInventarioMedicoRoute
  '/_authenticated/salud-ocupacional/mis-consultas': typeof AuthenticatedSaludOcupacionalMisConsultasRoute
  '/_authenticated/salud-ocupacional/registro-consulta': typeof AuthenticatedSaludOcupacionalRegistroConsultaRoute
  '/_authenticated/salud-ocupacional/reportes': typeof AuthenticatedSaludOcupacionalReportesRoute
  '/_authenticated/sistemas/ajustes': typeof AuthenticatedSistemasAjustesRoute
  '/_authenticated/sistemas/asignacion-bienes': typeof AuthenticatedSistemasAsignacionBienesRoute
  '/_authenticated/sistemas/mis-equipos': typeof AuthenticatedSistemasMisEquiposRoute
  '/_authenticated/sistemas/registro-productividad': typeof AuthenticatedSistemasRegistroProductividadRoute
  '/_authenticated/visitas/portal-central': typeof AuthenticatedVisitasPortalCentralRoute
  '/_authenticated/visitas/registro-visita': typeof AuthenticatedVisitasRegistroVisitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mi-firma'
    | '/administracion/ajustes'
    | '/administracion/asignaciones'
    | '/administracion/gestion-usuarios'
    | '/administracion/roles'
    | '/crm-quimicos/dashboard-crm'
    | '/horas-extra/ajustes'
    | '/horas-extra/aprobacion-horas-extra'
    | '/horas-extra/registro-horas-extra'
    | '/salud-ocupacional/ajustes'
    | '/salud-ocupacional/descanso-medico'
    | '/salud-ocupacional/historial-medico'
    | '/salud-ocupacional/inventario-medico'
    | '/salud-ocupacional/mis-consultas'
    | '/salud-ocupacional/registro-consulta'
    | '/salud-ocupacional/reportes'
    | '/sistemas/ajustes'
    | '/sistemas/asignacion-bienes'
    | '/sistemas/mis-equipos'
    | '/sistemas/registro-productividad'
    | '/visitas/portal-central'
    | '/visitas/registro-visita'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mi-firma'
    | '/administracion/ajustes'
    | '/administracion/asignaciones'
    | '/administracion/gestion-usuarios'
    | '/administracion/roles'
    | '/crm-quimicos/dashboard-crm'
    | '/horas-extra/ajustes'
    | '/horas-extra/aprobacion-horas-extra'
    | '/horas-extra/registro-horas-extra'
    | '/salud-ocupacional/ajustes'
    | '/salud-ocupacional/descanso-medico'
    | '/salud-ocupacional/historial-medico'
    | '/salud-ocupacional/inventario-medico'
    | '/salud-ocupacional/mis-consultas'
    | '/salud-ocupacional/registro-consulta'
    | '/salud-ocupacional/reportes'
    | '/sistemas/ajustes'
    | '/sistemas/asignacion-bienes'
    | '/sistemas/mis-equipos'
    | '/sistemas/registro-productividad'
    | '/visitas/portal-central'
    | '/visitas/registro-visita'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/mi-firma'
    | '/_authenticated/administracion/ajustes'
    | '/_authenticated/administracion/asignaciones'
    | '/_authenticated/administracion/gestion-usuarios'
    | '/_authenticated/administracion/roles'
    | '/_authenticated/crm-quimicos/dashboard-crm'
    | '/_authenticated/horas-extra/ajustes'
    | '/_authenticated/horas-extra/aprobacion-horas-extra'
    | '/_authenticated/horas-extra/registro-horas-extra'
    | '/_authenticated/salud-ocupacional/ajustes'
    | '/_authenticated/salud-ocupacional/descanso-medico'
    | '/_authenticated/salud-ocupacional/historial-medico'
    | '/_authenticated/salud-ocupacional/inventario-medico'
    | '/_authenticated/salud-ocupacional/mis-consultas'
    | '/_authenticated/salud-ocupacional/registro-consulta'
    | '/_authenticated/salud-ocupacional/reportes'
    | '/_authenticated/sistemas/ajustes'
    | '/_authenticated/sistemas/asignacion-bienes'
    | '/_authenticated/sistemas/mis-equipos'
    | '/_authenticated/sistemas/registro-productividad'
    | '/_authenticated/visitas/portal-central'
    | '/_authenticated/visitas/registro-visita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-firma': {
      id: '/_authenticated/mi-firma'
      path: '/mi-firma'
      fullPath: '/mi-firma'
      preLoaderRoute: typeof AuthenticatedMiFirmaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitas/registro-visita': {
      id: '/_authenticated/visitas/registro-visita'
      path: '/visitas/registro-visita'
      fullPath: '/visitas/registro-visita'
      preLoaderRoute: typeof AuthenticatedVisitasRegistroVisitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitas/portal-central': {
      id: '/_authenticated/visitas/portal-central'
      path: '/visitas/portal-central'
      fullPath: '/visitas/portal-central'
      preLoaderRoute: typeof AuthenticatedVisitasPortalCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistemas/registro-productividad': {
      id: '/_authenticated/sistemas/registro-productividad'
      path: '/sistemas/registro-productividad'
      fullPath: '/sistemas/registro-productividad'
      preLoaderRoute: typeof AuthenticatedSistemasRegistroProductividadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistemas/mis-equipos': {
      id: '/_authenticated/sistemas/mis-equipos'
      path: '/sistemas/mis-equipos'
      fullPath: '/sistemas/mis-equipos'
      preLoaderRoute: typeof AuthenticatedSistemasMisEquiposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistemas/asignacion-bienes': {
      id: '/_authenticated/sistemas/asignacion-bienes'
      path: '/sistemas/asignacion-bienes'
      fullPath: '/sistemas/asignacion-bienes'
      preLoaderRoute: typeof AuthenticatedSistemasAsignacionBienesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistemas/ajustes': {
      id: '/_authenticated/sistemas/ajustes'
      path: '/sistemas/ajustes'
      fullPath: '/sistemas/ajustes'
      preLoaderRoute: typeof AuthenticatedSistemasAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/reportes': {
      id: '/_authenticated/salud-ocupacional/reportes'
      path: '/salud-ocupacional/reportes'
      fullPath: '/salud-ocupacional/reportes'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/registro-consulta': {
      id: '/_authenticated/salud-ocupacional/registro-consulta'
      path: '/salud-ocupacional/registro-consulta'
      fullPath: '/salud-ocupacional/registro-consulta'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalRegistroConsultaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/mis-consultas': {
      id: '/_authenticated/salud-ocupacional/mis-consultas'
      path: '/salud-ocupacional/mis-consultas'
      fullPath: '/salud-ocupacional/mis-consultas'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalMisConsultasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/inventario-medico': {
      id: '/_authenticated/salud-ocupacional/inventario-medico'
      path: '/salud-ocupacional/inventario-medico'
      fullPath: '/salud-ocupacional/inventario-medico'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalInventarioMedicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/historial-medico': {
      id: '/_authenticated/salud-ocupacional/historial-medico'
      path: '/salud-ocupacional/historial-medico'
      fullPath: '/salud-ocupacional/historial-medico'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalHistorialMedicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/descanso-medico': {
      id: '/_authenticated/salud-ocupacional/descanso-medico'
      path: '/salud-ocupacional/descanso-medico'
      fullPath: '/salud-ocupacional/descanso-medico'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalDescansoMedicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud-ocupacional/ajustes': {
      id: '/_authenticated/salud-ocupacional/ajustes'
      path: '/salud-ocupacional/ajustes'
      fullPath: '/salud-ocupacional/ajustes'
      preLoaderRoute: typeof AuthenticatedSaludOcupacionalAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas-extra/registro-horas-extra': {
      id: '/_authenticated/horas-extra/registro-horas-extra'
      path: '/horas-extra/registro-horas-extra'
      fullPath: '/horas-extra/registro-horas-extra'
      preLoaderRoute: typeof AuthenticatedHorasExtraRegistroHorasExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas-extra/aprobacion-horas-extra': {
      id: '/_authenticated/horas-extra/aprobacion-horas-extra'
      path: '/horas-extra/aprobacion-horas-extra'
      fullPath: '/horas-extra/aprobacion-horas-extra'
      preLoaderRoute: typeof AuthenticatedHorasExtraAprobacionHorasExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas-extra/ajustes': {
      id: '/_authenticated/horas-extra/ajustes'
      path: '/horas-extra/ajustes'
      fullPath: '/horas-extra/ajustes'
      preLoaderRoute: typeof AuthenticatedHorasExtraAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm-quimicos/dashboard-crm': {
      id: '/_authenticated/crm-quimicos/dashboard-crm'
      path: '/crm-quimicos/dashboard-crm'
      fullPath: '/crm-quimicos/dashboard-crm'
      preLoaderRoute: typeof AuthenticatedCrmQuimicosDashboardCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracion/roles': {
      id: '/_authenticated/administracion/roles'
      path: '/administracion/roles'
      fullPath: '/administracion/roles'
      preLoaderRoute: typeof AuthenticatedAdministracionRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracion/gestion-usuarios': {
      id: '/_authenticated/administracion/gestion-usuarios'
      path: '/administracion/gestion-usuarios'
      fullPath: '/administracion/gestion-usuarios'
      preLoaderRoute: typeof AuthenticatedAdministracionGestionUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracion/asignaciones': {
      id: '/_authenticated/administracion/asignaciones'
      path: '/administracion/asignaciones'
      fullPath: '/administracion/asignaciones'
      preLoaderRoute: typeof AuthenticatedAdministracionAsignacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracion/ajustes': {
      id: '/_authenticated/administracion/ajustes'
      path: '/administracion/ajustes'
      fullPath: '/administracion/ajustes'
      preLoaderRoute: typeof AuthenticatedAdministracionAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMiFirmaRoute: typeof AuthenticatedMiFirmaRoute
  AuthenticatedAdministracionAjustesRoute: typeof AuthenticatedAdministracionAjustesRoute
  AuthenticatedAdministracionAsignacionesRoute: typeof AuthenticatedAdministracionAsignacionesRoute
  AuthenticatedAdministracionGestionUsuariosRoute: typeof AuthenticatedAdministracionGestionUsuariosRoute
  AuthenticatedAdministracionRolesRoute: typeof AuthenticatedAdministracionRolesRoute
  AuthenticatedCrmQuimicosDashboardCrmRoute: typeof AuthenticatedCrmQuimicosDashboardCrmRoute
  AuthenticatedHorasExtraAjustesRoute: typeof AuthenticatedHorasExtraAjustesRoute
  AuthenticatedHorasExtraAprobacionHorasExtraRoute: typeof AuthenticatedHorasExtraAprobacionHorasExtraRoute
  AuthenticatedHorasExtraRegistroHorasExtraRoute: typeof AuthenticatedHorasExtraRegistroHorasExtraRoute
  AuthenticatedSaludOcupacionalAjustesRoute: typeof AuthenticatedSaludOcupacionalAjustesRoute
  AuthenticatedSaludOcupacionalDescansoMedicoRoute: typeof AuthenticatedSaludOcupacionalDescansoMedicoRoute
  AuthenticatedSaludOcupacionalHistorialMedicoRoute: typeof AuthenticatedSaludOcupacionalHistorialMedicoRoute
  AuthenticatedSaludOcupacionalInventarioMedicoRoute: typeof AuthenticatedSaludOcupacionalInventarioMedicoRoute
  AuthenticatedSaludOcupacionalMisConsultasRoute: typeof AuthenticatedSaludOcupacionalMisConsultasRoute
  AuthenticatedSaludOcupacionalRegistroConsultaRoute: typeof AuthenticatedSaludOcupacionalRegistroConsultaRoute
  AuthenticatedSaludOcupacionalReportesRoute: typeof AuthenticatedSaludOcupacionalReportesRoute
  AuthenticatedSistemasAjustesRoute: typeof AuthenticatedSistemasAjustesRoute
  AuthenticatedSistemasAsignacionBienesRoute: typeof AuthenticatedSistemasAsignacionBienesRoute
  AuthenticatedSistemasMisEquiposRoute: typeof AuthenticatedSistemasMisEquiposRoute
  AuthenticatedSistemasRegistroProductividadRoute: typeof AuthenticatedSistemasRegistroProductividadRoute
  AuthenticatedVisitasPortalCentralRoute: typeof AuthenticatedVisitasPortalCentralRoute
  AuthenticatedVisitasRegistroVisitaRoute: typeof AuthenticatedVisitasRegistroVisitaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMiFirmaRoute: AuthenticatedMiFirmaRoute,
  AuthenticatedAdministracionAjustesRoute:
    AuthenticatedAdministracionAjustesRoute,
  AuthenticatedAdministracionAsignacionesRoute:
    AuthenticatedAdministracionAsignacionesRoute,
  AuthenticatedAdministracionGestionUsuariosRoute:
    AuthenticatedAdministracionGestionUsuariosRoute,
  AuthenticatedAdministracionRolesRoute: AuthenticatedAdministracionRolesRoute,
  AuthenticatedCrmQuimicosDashboardCrmRoute:
    AuthenticatedCrmQuimicosDashboardCrmRoute,
  AuthenticatedHorasExtraAjustesRoute: AuthenticatedHorasExtraAjustesRoute,
  AuthenticatedHorasExtraAprobacionHorasExtraRoute:
    AuthenticatedHorasExtraAprobacionHorasExtraRoute,
  AuthenticatedHorasExtraRegistroHorasExtraRoute:
    AuthenticatedHorasExtraRegistroHorasExtraRoute,
  AuthenticatedSaludOcupacionalAjustesRoute:
    AuthenticatedSaludOcupacionalAjustesRoute,
  AuthenticatedSaludOcupacionalDescansoMedicoRoute:
    AuthenticatedSaludOcupacionalDescansoMedicoRoute,
  AuthenticatedSaludOcupacionalHistorialMedicoRoute:
    AuthenticatedSaludOcupacionalHistorialMedicoRoute,
  AuthenticatedSaludOcupacionalInventarioMedicoRoute:
    AuthenticatedSaludOcupacionalInventarioMedicoRoute,
  AuthenticatedSaludOcupacionalMisConsultasRoute:
    AuthenticatedSaludOcupacionalMisConsultasRoute,
  AuthenticatedSaludOcupacionalRegistroConsultaRoute:
    AuthenticatedSaludOcupacionalRegistroConsultaRoute,
  AuthenticatedSaludOcupacionalReportesRoute:
    AuthenticatedSaludOcupacionalReportesRoute,
  AuthenticatedSistemasAjustesRoute: AuthenticatedSistemasAjustesRoute,
  AuthenticatedSistemasAsignacionBienesRoute:
    AuthenticatedSistemasAsignacionBienesRoute,
  AuthenticatedSistemasMisEquiposRoute: AuthenticatedSistemasMisEquiposRoute,
  AuthenticatedSistemasRegistroProductividadRoute:
    AuthenticatedSistemasRegistroProductividadRoute,
  AuthenticatedVisitasPortalCentralRoute:
    AuthenticatedVisitasPortalCentralRoute,
  AuthenticatedVisitasRegistroVisitaRoute:
    AuthenticatedVisitasRegistroVisitaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
